version: 2.1

executors:
  python:
    docker:
      - image: circleci/python:3.7.5-stretch

defaults: &defaults
  executor: python

orbs:
  docker: circleci/docker@0.5.20


jobs:

  build:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Install Dependencies
          command: |
            pip install --user -r .circleci/requirements.txt
      - run:
          name: Build Image
          command: |
            neuro config login-with-token $NEURO_TOKEN
            neuro config docker
            export IMAGE_NAME=neuromation/ml-recipe-object-detection
            export IMAGE_REF=$IMAGE_NAME:$CIRCLE_BUILD_NUM
            export IMAGE_URI=image:$IMAGE_REF
            make setup \
                __BAKE_SETUP=yes \
                CUSTOM_ENV_NAME=$IMAGE_URI \
                PROJECT_PATH_STORAGE=storage:$(uuidgen)
            neuro pull $IMAGE_URI
            # docker tag $IMAGE_REF $IMAGE_NAME:$CIRCLE_TAG
            docker tag $IMAGE_REF $IMAGE_NAME:latest
      - docker/check
      - docker/push:
          image: neuromation/ml-recipe-object-detection
          tag: latest


workflows:
  version: 2

  main:
    jobs:
      - build:
          filters:
            branches:
              ignore: /TODO.*/
            tags:
              only:
                - /.*/
